### ISSUE TITLE
Error on NPM install on MacOS

### ISSUE THREAD

**Issue by johndierks** [phonezawphyo/monkey-opencv#1]
I'm trying to install on Mac OS Sierra

`npm install --save monkey-opencv`

Getting the following output. Any thoughts?
```

npm WARN package.json template-match-test@1.0.0 No description
npm WARN package.json template-match-test@1.0.0 No repository field.
npm WARN package.json template-match-test@1.0.0 No README data
|
> monkey-opencv@1.0.1 install /Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-fast-template-matcher.s3-us-west-2.amazonaws.com/monkey_opencv/v1.0.1/Release/node-v46-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for monkey-opencv@1.0.1 and node@4.2.2 (node-v46 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/monkey_opencv/src/addon.o
  CXX(target) Release/obj.target/monkey_opencv/src/template_matcher.o
../src/template_matcher.cc:24:9: error: no member named 'matchTemplate' in namespace 'cv'
    cv::matchTemplate(copyOfSource,
    ~~~~^
../src/template_matcher.cc:74:9: error: no member named 'pyrDown' in namespace 'cv'
    cv::pyrDown(imageCopy, smallImage);
    ~~~~^
../src/template_matcher.cc:191:7: error: no member named 'matchTemplate' in namespace 'cv'
  cv::matchTemplate(img, target, result, method);
  ~~~~^
3 errors generated.
make: *** [Release/obj.target/monkey_opencv/src/template_matcher.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/john/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/john/.nvm/versions/node/v4.2.2/bin/node" "/Users/john/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/build/monkey_opencv/v1.0.1/Release/node-v46-darwin-x64/monkey_opencv.node" "--module_name=monkey_opencv" "--module_path=/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/build/monkey_opencv/v1.0.1/Release/node-v46-darwin-x64"
gyp ERR! cwd /Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/john/.nvm/versions/node/v4.2.2/bin/node /Users/john/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/build/monkey_opencv/v1.0.1/Release/node-v46-darwin-x64/monkey_opencv.node --module_name=monkey_opencv --module_path=/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/build/monkey_opencv/v1.0.1/Release/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.1.0
node-pre-gyp ERR! command "/Users/john/.nvm/versions/node/v4.2.2/bin/node" "/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/Users/john/.nvm/versions/node/v4.2.2/bin/node /Users/john/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/build/monkey_opencv/v1.0.1/Release/node-v46-darwin-x64/monkey_opencv.node --module_name=monkey_opencv --module_path=/Users/john/dev/ps/templateMatchTest/node_modules/monkey-opencv/build/monkey_opencv/v1.0.1/Release/node-v46-darwin-x64' (1)
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/john/.nvm/versions/node/v4.2.2/bin/node" "/Users/john/.nvm/versions/node/v4.2.2/bin/npm" "install" "--save" "monkey-opencv"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! monkey-opencv@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the monkey-opencv@1.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the monkey-opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls monkey-opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/john/dev/ps/templateMatchTest/npm-debug.log
```

**Comment by phonezawphyo** [comment]
It seems like an OpenCV error.
Do you have opencv installed in your computer?

 It requires opencv to build native binaries.
http://seeb0h.github.io/howto/howto-install-homebrew-python-opencv-osx-el-capitan/

**Comment by johndierks** [comment]
Thanks, yeah, it was installed but there were errors with the links. Everything is working now.
